### ISSUE TITLE
Enhancement: Patreon

### ISSUE THREAD

**Issue by cathalgarvey** [hughperkins/tensorflow-cl#12]
I wasn't kidding in the Tensorflow discussion; I use a bunch of software that you maintain, including the CL ports of Torch7. Soon, I hope to be able to use Tensorflow thanks to your efforts. I bought an AMD GPU rather than a NVidia because I believe in open standards, and also because I could see a handful of dedicated people were working on OpenCL ports of the big frameworks; chiefly yourself.

Well, buying AMD saved me literally hundreds of Euro for the same performance. Please give me a chance to contribute some of that saving towards your efforts, as a way to say thank-you. :)

**Comment by hughperkins** [comment]
Well, there are various reasons why accepting remuneration would probably be complicated.  So I shall avoid that.

What oculd be useful could be access to an AMD gpu occasionally.  I cant say I really want to ssh into someone else's computer. but you could maybe install an os to usb key, and temporarily disable the hard drive in the bios or something, so that I could ssh into some pristine os, that you could rewipe afterwards, or at least simply unplug, and turn back on the harddrvei in the bios, and return to your normal os.

Thank you very much for your words of encouragement by the way.  Very much appreciated :-)

**Comment by Mandrewoid** [comment]
Hugh, I would be willing to do exactly that if you want. I have a Radeon HD 7950 and a Radeon HD 5850

**Comment by hughperkins** [comment]
I have access to a Radeon on a Mac now. But... a question in my mind: what is the current status of the codeplay tensorflow?  To what extent does it do what one needs? (If it already does what one needs, I might just leave them to handle that, seems no point in duplicating effort too much :-) )

**Comment by cathalgarvey** [comment]
Just bumping this to say; my interest in helping to financially support the development of Coriander remains strong.

More feedback on Codeplay's 'solution': It doesn't support cards like the R9 390, which was only released in 2015 and is hardly "old". There are lots of these cards available affordably thanks to the ongoing FLOPS war in cryptocurrency-land, and they can all be put to good use thanks to Coriander. I think this is very important work.

**Comment by hughperkins** [comment]
> More feedback on Codeplay's 'solution': It doesn't support cards like the R9 390, which was only released in 2015 and is hardly "old". There are lots of these cards available affordably thanks to the ongoing FLOPS war in cryptocurrency-land, and they can all be put to good use thanks to Coriander. I think this is very important work.

Awesome, thanks!
