### ISSUE TITLE
Install fails with wheel error

### ISSUE THREAD

**Issue by Whytehorse** [hughperkins/tensorflow-cl#16]
Following the readme instructions for a standard install gives the following error on Ubuntu 16.04.
```
$ pip install --upgrade tensorflow-0.11.0rc0-py3-none-any.whl
tensorflow-0.11.0rc0-py3-none-any.whl is not a supported wheel on this platform.
```

I fixed it by using pip3 instead of pip.

**Comment by yarrseni** [comment]
You most probably are using pip from python2.7 since it is ubuntu and you  have some issues with virtual environment in a separate 'bug'. Try installing with `pip3 install --upgrade tensorflow-0.11.0rc0-py3-none-any.whl`, since the wheel you've mentioned is build for python3 (`-py3-` is telling it).
